
product_mapping = {
    '1S':{
        'product':'1S',
        'spread_name':'cv1',
        'outrights':['cv1'],
        'cfds':'SB-CFDS-CBT'},
    '1C':{
        'product':'1C', 
        'spread_name':'cv1', 
        'outrights':['cv1'], 
        'cfds':'CO-CFDS-CBT'},
    'SM':{
        'product':'SM', 
        'spread_name':'cv1', 
        'outrights':['cv1'], 
        'cfds':'SM-CFDS-CBT'},
    'BO':{
        'product':'BO',
        'spread_name':'cv1',
        'outrights':['cv1'],
        'cfds':'SO-CFDS-CBT'},
    '1W':{
        'product':'1W', 
        'spread_name':'cv1',
        'outrights':['cv1'],
        'cfds':'WH-CFDS-CBT'},
    'LCO':{
        'product':'LCO', 
        'spread_name':'cv1',
        'outrights':['cv1'],
        'cfds':None}

}


active_spreads = {
    '1S':[
        'F3-H3',
        'H3-K3',
        'K3-N3',
        'N3-X3',
        ],
    '1C':[
        'H3-K3',
        'K3-N3',
        'N3-U3',
        'U3-Z3',
        ],
    'SM':[
        'F3-H3',
        'H3-K3',
        'K3-N3',
        'N3-Z3',
        ],
    'BO':[
        'F3-H3',
        'H3-K3',
        'K3-N3',
        'N3-Z3',
        ],
    '1W':[
        'H3-K3',
        'K3-N3',
        'N3-U3',
        'U3-Z3',
        ],
    'LCO':[
        'H3-J3',
        'J3-K3',
        'K3-M3',
        'M3-N3',
        ],
}